/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.infobip.auth;

public enum OAuthFlow {
  accessCode, // called authorizationCode  in OpenAPI 3.0
  implicit,
  password,
  application // called clientCredentials in OpenAPI 3.0
}
