/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.infobip.model;

import com.google.gson.annotations.SerializedName;
import java.util.Objects;

/** ApiRequestErrorDetailsApiInfobipOrgInfobipapimanagementsms */
public class ApiRequestErrorDetailsApiInfobipOrgInfobipapimanagementsms {
  public static final String SERIALIZED_NAME_VARIABLES = "variables";

  @SerializedName(SERIALIZED_NAME_VARIABLES)
  private String variables;

  public static final String SERIALIZED_NAME_MESSAGE_ID = "messageId";

  @SerializedName(SERIALIZED_NAME_MESSAGE_ID)
  private String messageId;

  public static final String SERIALIZED_NAME_ADDITIONAL_DESCRIPTION = "additionalDescription";

  @SerializedName(SERIALIZED_NAME_ADDITIONAL_DESCRIPTION)
  private String additionalDescription;

  public static final String SERIALIZED_NAME_TEXT = "text";

  @SerializedName(SERIALIZED_NAME_TEXT)
  private String text;

  public ApiRequestErrorDetailsApiInfobipOrgInfobipapimanagementsms variables(String variables) {

    this.variables = variables;
    return this;
  }

  /**
   * Get variables
   *
   * @return variables
   */
  public String getVariables() {
    return variables;
  }

  public void setVariables(String variables) {
    this.variables = variables;
  }

  public ApiRequestErrorDetailsApiInfobipOrgInfobipapimanagementsms messageId(String messageId) {

    this.messageId = messageId;
    return this;
  }

  /**
   * Get messageId
   *
   * @return messageId
   */
  public String getMessageId() {
    return messageId;
  }

  public void setMessageId(String messageId) {
    this.messageId = messageId;
  }

  public ApiRequestErrorDetailsApiInfobipOrgInfobipapimanagementsms additionalDescription(
      String additionalDescription) {

    this.additionalDescription = additionalDescription;
    return this;
  }

  /**
   * Get additionalDescription
   *
   * @return additionalDescription
   */
  public String getAdditionalDescription() {
    return additionalDescription;
  }

  public void setAdditionalDescription(String additionalDescription) {
    this.additionalDescription = additionalDescription;
  }

  public ApiRequestErrorDetailsApiInfobipOrgInfobipapimanagementsms text(String text) {

    this.text = text;
    return this;
  }

  /**
   * Get text
   *
   * @return text
   */
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiRequestErrorDetailsApiInfobipOrgInfobipapimanagementsms
        apiRequestErrorDetailsApiInfobipOrgInfobipapimanagementsms =
            (ApiRequestErrorDetailsApiInfobipOrgInfobipapimanagementsms) o;
    return Objects.equals(
            this.variables, apiRequestErrorDetailsApiInfobipOrgInfobipapimanagementsms.variables)
        && Objects.equals(
            this.messageId, apiRequestErrorDetailsApiInfobipOrgInfobipapimanagementsms.messageId)
        && Objects.equals(
            this.additionalDescription,
            apiRequestErrorDetailsApiInfobipOrgInfobipapimanagementsms.additionalDescription)
        && Objects.equals(
            this.text, apiRequestErrorDetailsApiInfobipOrgInfobipapimanagementsms.text);
  }

  @Override
  public int hashCode() {
    return Objects.hash(variables, messageId, additionalDescription, text);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiRequestErrorDetailsApiInfobipOrgInfobipapimanagementsms {\n");
    sb.append("    variables: ").append(toIndentedString(variables)).append("\n");
    sb.append("    messageId: ").append(toIndentedString(messageId)).append("\n");
    sb.append("    additionalDescription: ")
        .append(toIndentedString(additionalDescription))
        .append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
