/*
 * This class is auto generated from the Infobip OpenAPI specification
 * through the OpenAPI Specification Client API libraries (Re)Generator (OSCAR),
 * powered by the OpenAPI Generator (https://openapi-generator.tech).
 *
 * Do not edit manually. To learn how to raise an issue, see the CONTRIBUTING guide
 * or contact us @ support@infobip.com.
 */

package com.infobip.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Type determining content of received event.
 */
public enum CallsEventType {
    DTMF_CAPTURED("DTMF_CAPTURED"),
    CALL_ESTABLISHED("CALL_ESTABLISHED"),
    CALL_PRE_ESTABLISHED("CALL_PRE_ESTABLISHED"),
    CALL_MEDIA_CHANGED("CALL_MEDIA_CHANGED"),
    CALL_FINISHED("CALL_FINISHED"),
    CALL_FAILED("CALL_FAILED"),
    CALL_RECEIVED("CALL_RECEIVED"),
    CALL_STARTED("CALL_STARTED"),
    CALL_RECORDING_STARTED("CALL_RECORDING_STARTED"),
    CALL_RECORDING_FAILED("CALL_RECORDING_FAILED"),
    CALL_RECORDING_READY("CALL_RECORDING_READY"),
    CALL_RECORDING_STOPPED("CALL_RECORDING_STOPPED"),
    CONFERENCE_RECORDING_STARTED("CONFERENCE_RECORDING_STARTED"),
    CONFERENCE_RECORDING_FAILED("CONFERENCE_RECORDING_FAILED"),
    CONFERENCE_RECORDING_READY("CONFERENCE_RECORDING_READY"),
    CONFERENCE_RECORDING_STOPPED("CONFERENCE_RECORDING_STOPPED"),
    CALL_RINGING("CALL_RINGING"),
    CONFERENCE_CREATED("CONFERENCE_CREATED"),
    CONFERENCE_FINISHED("CONFERENCE_FINISHED"),
    ERROR("ERROR"),
    PARTICIPANT_MEDIA_CHANGED("PARTICIPANT_MEDIA_CHANGED"),
    PARTICIPANT_JOIN_FAILED("PARTICIPANT_JOIN_FAILED"),
    PARTICIPANT_JOINED("PARTICIPANT_JOINED"),
    PARTICIPANT_JOINING("PARTICIPANT_JOINING"),
    PARTICIPANT_RECORDING_FAILED("PARTICIPANT_RECORDING_FAILED"),
    PARTICIPANT_REMOVED("PARTICIPANT_REMOVED"),
    PARTICIPANT_STARTED_TALKING("PARTICIPANT_STARTED_TALKING"),
    PARTICIPANT_STOPPED_TALKING("PARTICIPANT_STOPPED_TALKING"),
    PARTICIPANT_ROLE_CHANGED("PARTICIPANT_ROLE_CHANGED"),
    PARTICIPANT_ROLE_CHANGE_FAILED("PARTICIPANT_ROLE_CHANGE_FAILED"),
    PLAY_FINISHED("PLAY_FINISHED"),
    CONFERENCE_COMPOSITION_FAILED("CONFERENCE_COMPOSITION_FAILED"),
    CONFERENCE_COMPOSITION_FINISHED("CONFERENCE_COMPOSITION_FINISHED"),
    SAY_FINISHED("SAY_FINISHED"),
    MACHINE_DETECTION_FINISHED("MACHINE_DETECTION_FINISHED"),
    MACHINE_DETECTION_FAILED("MACHINE_DETECTION_FAILED"),
    MACHINE_MESSAGE_DETECTION_FINISHED("MACHINE_MESSAGE_DETECTION_FINISHED"),
    MACHINE_MESSAGE_DETECTION_FAILED("MACHINE_MESSAGE_DETECTION_FAILED"),
    MEDIA_STREAM_STARTED("MEDIA_STREAM_STARTED"),
    MEDIA_STREAM_FAILED("MEDIA_STREAM_FAILED"),
    MEDIA_STREAM_FINISHED("MEDIA_STREAM_FINISHED"),
    APPLICATION_TRANSFER_REQUESTED("APPLICATION_TRANSFER_REQUESTED"),
    APPLICATION_TRANSFER_FAILED("APPLICATION_TRANSFER_FAILED"),
    APPLICATION_TRANSFER_FINISHED("APPLICATION_TRANSFER_FINISHED"),
    DIALOG_CREATED("DIALOG_CREATED"),
    DIALOG_ESTABLISHED("DIALOG_ESTABLISHED"),
    DIALOG_FAILED("DIALOG_FAILED"),
    DIALOG_FINISHED("DIALOG_FINISHED"),
    DIALOG_RECORDING_STARTED("DIALOG_RECORDING_STARTED"),
    DIALOG_RECORDING_FAILED("DIALOG_RECORDING_FAILED"),
    DIALOG_RECORDING_READY("DIALOG_RECORDING_READY"),
    DIALOG_RECORDING_STOPPED("DIALOG_RECORDING_STOPPED"),
    DIALOG_COMPOSITION_FAILED("DIALOG_COMPOSITION_FAILED"),
    DIALOG_COMPOSITION_FINISHED("DIALOG_COMPOSITION_FINISHED"),
    TRANSCRIPTION("TRANSCRIPTION"),
    SPEECH_CAPTURED("SPEECH_CAPTURED"),
    BULK_CALL_STATUS("BULK_CALL_STATUS"),
    CONFERENCE_RECORDING_DELETED("CONFERENCE_RECORDING_DELETED"),
    DIALOG_RECORDING_DELETED("DIALOG_RECORDING_DELETED"),
    CALL_RECORDING_DELETED("CALL_RECORDING_DELETED"),
    CALL_DISCONNECTED("CALL_DISCONNECTED"),
    CALL_RECONNECTED("CALL_RECONNECTED"),
    DIALOG_TRANSFER_REQUESTED("DIALOG_TRANSFER_REQUESTED"),
    DIALOG_TRANSFER_FAILED("DIALOG_TRANSFER_FAILED"),
    DIALOG_TRANSFER_FINISHED("DIALOG_TRANSFER_FINISHED");

    private final String value;

    CallsEventType(String value) {
        this.value = value;
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
    public static CallsEventType fromValue(String value) {
        for (CallsEventType enumElement : CallsEventType.values()) {
            if (enumElement.value.equals(value)) {
                return enumElement;
            }
        }
        throw new IllegalArgumentException("Unexpected enum value '" + value + "'.");
    }
}
