/*
 * This class is auto generated from the Infobip OpenAPI specification
 * through the OpenAPI Specification Client API libraries (Re)Generator (OSCAR),
 * powered by the OpenAPI Generator (https://openapi-generator.tech).
 *
 * Do not edit manually. To learn how to raise an issue, see the CONTRIBUTING guide
 * or contact us @ support@infobip.com.
 */

package com.infobip.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Represents EmailSendMimeRequestSchema model.
 */
public class EmailSendMimeRequestSchema {

    private String messageId;

    private String bulkId;

    private String from;

    private List<String> destinations = null;

    private String mimeMessage;

    private Boolean intermediateReport;

    private String notifyUrl;

    private String notifyContentType;

    private String callbackData;

    private String trackingUrl;

    private String clientPriority;

    private String applicationId;

    private String entityId;

    /**
     * Sets messageId.
     * <p>
     * Field description:
     * The ID that uniquely identifies the message sent to a recipient.
     *
     * @param messageId
     * @return This {@link EmailSendMimeRequestSchema instance}.
     */
    public EmailSendMimeRequestSchema messageId(String messageId) {
        this.messageId = messageId;
        return this;
    }

    /**
     * Returns messageId.
     * <p>
     * Field description:
     * The ID that uniquely identifies the message sent to a recipient.
     *
     * @return messageId
     */
    @JsonProperty("messageId")
    public String getMessageId() {
        return messageId;
    }

    /**
     * Sets messageId.
     * <p>
     * Field description:
     * The ID that uniquely identifies the message sent to a recipient.
     *
     * @param messageId
     */
    @JsonProperty("messageId")
    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }

    /**
     * Sets bulkId.
     * <p>
     * Field description:
     * The ID that uniquely identifies the sent bulk. This filter will enable you to query delivery reports for all the messages using just one request. You will receive a &#x60;bulkId&#x60; in the response after sending an email request. If you don&#39;t set your own &#x60;bulkId&#x60;, unique ID will be generated by our system and returned in the API response. (Optional Field)\&quot;)
     *
     * @param bulkId
     * @return This {@link EmailSendMimeRequestSchema instance}.
     */
    public EmailSendMimeRequestSchema bulkId(String bulkId) {
        this.bulkId = bulkId;
        return this;
    }

    /**
     * Returns bulkId.
     * <p>
     * Field description:
     * The ID that uniquely identifies the sent bulk. This filter will enable you to query delivery reports for all the messages using just one request. You will receive a &#x60;bulkId&#x60; in the response after sending an email request. If you don&#39;t set your own &#x60;bulkId&#x60;, unique ID will be generated by our system and returned in the API response. (Optional Field)\&quot;)
     *
     * @return bulkId
     */
    @JsonProperty("bulkId")
    public String getBulkId() {
        return bulkId;
    }

    /**
     * Sets bulkId.
     * <p>
     * Field description:
     * The ID that uniquely identifies the sent bulk. This filter will enable you to query delivery reports for all the messages using just one request. You will receive a &#x60;bulkId&#x60; in the response after sending an email request. If you don&#39;t set your own &#x60;bulkId&#x60;, unique ID will be generated by our system and returned in the API response. (Optional Field)\&quot;)
     *
     * @param bulkId
     */
    @JsonProperty("bulkId")
    public void setBulkId(String bulkId) {
        this.bulkId = bulkId;
    }

    /**
     * Sets from.
     * <p>
     * Field description:
     * The email address specified in this field takes precedence over the From header in the MIME message. If you leave this field empty, the From address in the MIME message will be used instead. If you provide both values and they are different, their domains must match at the organizational level; otherwise, the request will be rejected.
     *
     * @param from
     * @return This {@link EmailSendMimeRequestSchema instance}.
     */
    public EmailSendMimeRequestSchema from(String from) {
        this.from = from;
        return this;
    }

    /**
     * Returns from.
     * <p>
     * Field description:
     * The email address specified in this field takes precedence over the From header in the MIME message. If you leave this field empty, the From address in the MIME message will be used instead. If you provide both values and they are different, their domains must match at the organizational level; otherwise, the request will be rejected.
     *
     * @return from
     */
    @JsonProperty("from")
    public String getFrom() {
        return from;
    }

    /**
     * Sets from.
     * <p>
     * Field description:
     * The email address specified in this field takes precedence over the From header in the MIME message. If you leave this field empty, the From address in the MIME message will be used instead. If you provide both values and they are different, their domains must match at the organizational level; otherwise, the request will be rejected.
     *
     * @param from
     */
    @JsonProperty("from")
    public void setFrom(String from) {
        this.from = from;
    }

    /**
     * Sets destinations.
     * <p>
     * Field description:
     * A list of recipient email addresses. &lt;br/&gt; The email addresses specified in this field takes precedence over the To, CC, and BCC headers in the MIME message. Only the addresses in this list will receive the final email. If you leave this field empty, To, CC, and BCC headers in the MIME message will be used instead. &lt;br/&gt; Note: Maximum number of recipients per request is 1000 overall including to, cc and bcc field.
     *
     * @param destinations
     * @return This {@link EmailSendMimeRequestSchema instance}.
     */
    public EmailSendMimeRequestSchema destinations(List<String> destinations) {
        this.destinations = destinations;
        return this;
    }

    /**
     * Adds and item into destinations.
     * <p>
     * Field description:
     * A list of recipient email addresses. &lt;br/&gt; The email addresses specified in this field takes precedence over the To, CC, and BCC headers in the MIME message. Only the addresses in this list will receive the final email. If you leave this field empty, To, CC, and BCC headers in the MIME message will be used instead. &lt;br/&gt; Note: Maximum number of recipients per request is 1000 overall including to, cc and bcc field.
     *
     * @param destinationsItem The item to be added to the list.
     * @return This {@link EmailSendMimeRequestSchema instance}.
     */
    public EmailSendMimeRequestSchema addDestinationsItem(String destinationsItem) {
        if (this.destinations == null) {
            this.destinations = new ArrayList<>();
        }
        this.destinations.add(destinationsItem);
        return this;
    }

    /**
     * Returns destinations.
     * <p>
     * Field description:
     * A list of recipient email addresses. &lt;br/&gt; The email addresses specified in this field takes precedence over the To, CC, and BCC headers in the MIME message. Only the addresses in this list will receive the final email. If you leave this field empty, To, CC, and BCC headers in the MIME message will be used instead. &lt;br/&gt; Note: Maximum number of recipients per request is 1000 overall including to, cc and bcc field.
     *
     * @return destinations
     */
    @JsonProperty("destinations")
    public List<String> getDestinations() {
        return destinations;
    }

    /**
     * Sets destinations.
     * <p>
     * Field description:
     * A list of recipient email addresses. &lt;br/&gt; The email addresses specified in this field takes precedence over the To, CC, and BCC headers in the MIME message. Only the addresses in this list will receive the final email. If you leave this field empty, To, CC, and BCC headers in the MIME message will be used instead. &lt;br/&gt; Note: Maximum number of recipients per request is 1000 overall including to, cc and bcc field.
     *
     * @param destinations
     */
    @JsonProperty("destinations")
    public void setDestinations(List<String> destinations) {
        this.destinations = destinations;
    }

    /**
     * Sets mimeMessage.
     * <p>
     * Field description:
     * This field accepts a complete email message serialized in the MIME format, conforming to RFC 5322 and MIME-related standards (RFCs 2045–2047, RFC 2183). The MIME message must be correctly constructed per the following requirements as if it were being sent via traditional SMTP. The entire MIME message (including headers and body) must be &#x60;base64-encoded&#x60; before being sent. &lt;br/&gt;&lt;br/&gt;  When using this field, these are the requirements: &lt;br/&gt; **-** The message must consist of a set of header fields, followed by a blank line (CRLF), and then the message body &lt;br/&gt; **-** All required and optional fields must be properly formatted with header-name, colon, and header-value &lt;br/&gt; **-** If any MIME part contains non-7-bit-ASCII data (e.g., UTF-8 text, binaries), that part must be encoded &lt;br/&gt; **-** If your message uses multipart content (attachments, alternative bodies, etc.), each MIME part must contain &#x60;Content-Type&#x60; header. For encoded parts, include &#x60;Content-Transfer-Encoding&#x60;. For attachments, include a valid &#x60;Content-Disposition&#x60;. &lt;br/&gt;&lt;br/&gt; We also support specifying additional headers in your MIME message, such as &#x60;List-Unsubscribe&#x60;, &#x60;List-Unsubscribe-Post&#x60;, &#x60;In-Reply-To&#x60;, &#x60;References&#x60; and &#x60;Message-ID&#x60;.
     * <p>
     * The field is required.
     *
     * @param mimeMessage
     * @return This {@link EmailSendMimeRequestSchema instance}.
     */
    public EmailSendMimeRequestSchema mimeMessage(String mimeMessage) {
        this.mimeMessage = mimeMessage;
        return this;
    }

    /**
     * Returns mimeMessage.
     * <p>
     * Field description:
     * This field accepts a complete email message serialized in the MIME format, conforming to RFC 5322 and MIME-related standards (RFCs 2045–2047, RFC 2183). The MIME message must be correctly constructed per the following requirements as if it were being sent via traditional SMTP. The entire MIME message (including headers and body) must be &#x60;base64-encoded&#x60; before being sent. &lt;br/&gt;&lt;br/&gt;  When using this field, these are the requirements: &lt;br/&gt; **-** The message must consist of a set of header fields, followed by a blank line (CRLF), and then the message body &lt;br/&gt; **-** All required and optional fields must be properly formatted with header-name, colon, and header-value &lt;br/&gt; **-** If any MIME part contains non-7-bit-ASCII data (e.g., UTF-8 text, binaries), that part must be encoded &lt;br/&gt; **-** If your message uses multipart content (attachments, alternative bodies, etc.), each MIME part must contain &#x60;Content-Type&#x60; header. For encoded parts, include &#x60;Content-Transfer-Encoding&#x60;. For attachments, include a valid &#x60;Content-Disposition&#x60;. &lt;br/&gt;&lt;br/&gt; We also support specifying additional headers in your MIME message, such as &#x60;List-Unsubscribe&#x60;, &#x60;List-Unsubscribe-Post&#x60;, &#x60;In-Reply-To&#x60;, &#x60;References&#x60; and &#x60;Message-ID&#x60;.
     * <p>
     * The field is required.
     *
     * @return mimeMessage
     */
    @JsonProperty("mimeMessage")
    public String getMimeMessage() {
        return mimeMessage;
    }

    /**
     * Sets mimeMessage.
     * <p>
     * Field description:
     * This field accepts a complete email message serialized in the MIME format, conforming to RFC 5322 and MIME-related standards (RFCs 2045–2047, RFC 2183). The MIME message must be correctly constructed per the following requirements as if it were being sent via traditional SMTP. The entire MIME message (including headers and body) must be &#x60;base64-encoded&#x60; before being sent. &lt;br/&gt;&lt;br/&gt;  When using this field, these are the requirements: &lt;br/&gt; **-** The message must consist of a set of header fields, followed by a blank line (CRLF), and then the message body &lt;br/&gt; **-** All required and optional fields must be properly formatted with header-name, colon, and header-value &lt;br/&gt; **-** If any MIME part contains non-7-bit-ASCII data (e.g., UTF-8 text, binaries), that part must be encoded &lt;br/&gt; **-** If your message uses multipart content (attachments, alternative bodies, etc.), each MIME part must contain &#x60;Content-Type&#x60; header. For encoded parts, include &#x60;Content-Transfer-Encoding&#x60;. For attachments, include a valid &#x60;Content-Disposition&#x60;. &lt;br/&gt;&lt;br/&gt; We also support specifying additional headers in your MIME message, such as &#x60;List-Unsubscribe&#x60;, &#x60;List-Unsubscribe-Post&#x60;, &#x60;In-Reply-To&#x60;, &#x60;References&#x60; and &#x60;Message-ID&#x60;.
     * <p>
     * The field is required.
     *
     * @param mimeMessage
     */
    @JsonProperty("mimeMessage")
    public void setMimeMessage(String mimeMessage) {
        this.mimeMessage = mimeMessage;
    }

    /**
     * Sets intermediateReport.
     * <p>
     * Field description:
     * The real-time Intermediate delivery report that will be sent on your callback server.
     *
     * @param intermediateReport
     * @return This {@link EmailSendMimeRequestSchema instance}.
     */
    public EmailSendMimeRequestSchema intermediateReport(Boolean intermediateReport) {
        this.intermediateReport = intermediateReport;
        return this;
    }

    /**
     * Returns intermediateReport.
     * <p>
     * Field description:
     * The real-time Intermediate delivery report that will be sent on your callback server.
     *
     * @return intermediateReport
     */
    @JsonProperty("intermediateReport")
    public Boolean getIntermediateReport() {
        return intermediateReport;
    }

    /**
     * Sets intermediateReport.
     * <p>
     * Field description:
     * The real-time Intermediate delivery report that will be sent on your callback server.
     *
     * @param intermediateReport
     */
    @JsonProperty("intermediateReport")
    public void setIntermediateReport(Boolean intermediateReport) {
        this.intermediateReport = intermediateReport;
    }

    /**
     * Sets notifyUrl.
     * <p>
     * Field description:
     * The URL on your callback server on which the Delivery report will be sent.
     *
     * @param notifyUrl
     * @return This {@link EmailSendMimeRequestSchema instance}.
     */
    public EmailSendMimeRequestSchema notifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl;
        return this;
    }

    /**
     * Returns notifyUrl.
     * <p>
     * Field description:
     * The URL on your callback server on which the Delivery report will be sent.
     *
     * @return notifyUrl
     */
    @JsonProperty("notifyUrl")
    public String getNotifyUrl() {
        return notifyUrl;
    }

    /**
     * Sets notifyUrl.
     * <p>
     * Field description:
     * The URL on your callback server on which the Delivery report will be sent.
     *
     * @param notifyUrl
     */
    @JsonProperty("notifyUrl")
    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl;
    }

    /**
     * Sets notifyContentType.
     * <p>
     * Field description:
     * Preferred Delivery report content type. Can be &#x60;application/json&#x60; or &#x60;application/xml&#x60;.
     *
     * @param notifyContentType
     * @return This {@link EmailSendMimeRequestSchema instance}.
     */
    public EmailSendMimeRequestSchema notifyContentType(String notifyContentType) {
        this.notifyContentType = notifyContentType;
        return this;
    }

    /**
     * Returns notifyContentType.
     * <p>
     * Field description:
     * Preferred Delivery report content type. Can be &#x60;application/json&#x60; or &#x60;application/xml&#x60;.
     *
     * @return notifyContentType
     */
    @JsonProperty("notifyContentType")
    public String getNotifyContentType() {
        return notifyContentType;
    }

    /**
     * Sets notifyContentType.
     * <p>
     * Field description:
     * Preferred Delivery report content type. Can be &#x60;application/json&#x60; or &#x60;application/xml&#x60;.
     *
     * @param notifyContentType
     */
    @JsonProperty("notifyContentType")
    public void setNotifyContentType(String notifyContentType) {
        this.notifyContentType = notifyContentType;
    }

    /**
     * Sets callbackData.
     * <p>
     * Field description:
     * Additional client data that will be sent on the notifyUrl.
     *
     * @param callbackData
     * @return This {@link EmailSendMimeRequestSchema instance}.
     */
    public EmailSendMimeRequestSchema callbackData(String callbackData) {
        this.callbackData = callbackData;
        return this;
    }

    /**
     * Returns callbackData.
     * <p>
     * Field description:
     * Additional client data that will be sent on the notifyUrl.
     *
     * @return callbackData
     */
    @JsonProperty("callbackData")
    public String getCallbackData() {
        return callbackData;
    }

    /**
     * Sets callbackData.
     * <p>
     * Field description:
     * Additional client data that will be sent on the notifyUrl.
     *
     * @param callbackData
     */
    @JsonProperty("callbackData")
    public void setCallbackData(String callbackData) {
        this.callbackData = callbackData;
    }

    /**
     * Sets trackingUrl.
     * <p>
     * Field description:
     * The URL on your callback server on which the open and click notifications will be sent. See [Tracking Notifications](https://www.infobip.com/docs/email/email-over-api/tracking-notifications) for details.
     *
     * @param trackingUrl
     * @return This {@link EmailSendMimeRequestSchema instance}.
     */
    public EmailSendMimeRequestSchema trackingUrl(String trackingUrl) {
        this.trackingUrl = trackingUrl;
        return this;
    }

    /**
     * Returns trackingUrl.
     * <p>
     * Field description:
     * The URL on your callback server on which the open and click notifications will be sent. See [Tracking Notifications](https://www.infobip.com/docs/email/email-over-api/tracking-notifications) for details.
     *
     * @return trackingUrl
     */
    @JsonProperty("trackingUrl")
    public String getTrackingUrl() {
        return trackingUrl;
    }

    /**
     * Sets trackingUrl.
     * <p>
     * Field description:
     * The URL on your callback server on which the open and click notifications will be sent. See [Tracking Notifications](https://www.infobip.com/docs/email/email-over-api/tracking-notifications) for details.
     *
     * @param trackingUrl
     */
    @JsonProperty("trackingUrl")
    public void setTrackingUrl(String trackingUrl) {
        this.trackingUrl = trackingUrl;
    }

    /**
     * Sets clientPriority.
     * <p>
     * Field description:
     * Adds a priority rating to this email message. Allowed values are &#x60;HIGH&#x60;, &#x60;STANDARD&#x60; and &#x60;LOW&#x60;. Messages with a higher priority value sent by your account are prioritized over messages with a lower priority value sent by your account. If no priority value is provided, messages will be treated with &#x60;STANDARD&#x60; priority by default.
     *
     * @param clientPriority
     * @return This {@link EmailSendMimeRequestSchema instance}.
     */
    public EmailSendMimeRequestSchema clientPriority(String clientPriority) {
        this.clientPriority = clientPriority;
        return this;
    }

    /**
     * Returns clientPriority.
     * <p>
     * Field description:
     * Adds a priority rating to this email message. Allowed values are &#x60;HIGH&#x60;, &#x60;STANDARD&#x60; and &#x60;LOW&#x60;. Messages with a higher priority value sent by your account are prioritized over messages with a lower priority value sent by your account. If no priority value is provided, messages will be treated with &#x60;STANDARD&#x60; priority by default.
     *
     * @return clientPriority
     */
    @JsonProperty("clientPriority")
    public String getClientPriority() {
        return clientPriority;
    }

    /**
     * Sets clientPriority.
     * <p>
     * Field description:
     * Adds a priority rating to this email message. Allowed values are &#x60;HIGH&#x60;, &#x60;STANDARD&#x60; and &#x60;LOW&#x60;. Messages with a higher priority value sent by your account are prioritized over messages with a lower priority value sent by your account. If no priority value is provided, messages will be treated with &#x60;STANDARD&#x60; priority by default.
     *
     * @param clientPriority
     */
    @JsonProperty("clientPriority")
    public void setClientPriority(String clientPriority) {
        this.clientPriority = clientPriority;
    }

    /**
     * Sets applicationId.
     * <p>
     * Field description:
     * Required for application use in a send request for outbound traffic. Returned in notification events.
     *
     * @param applicationId
     * @return This {@link EmailSendMimeRequestSchema instance}.
     */
    public EmailSendMimeRequestSchema applicationId(String applicationId) {
        this.applicationId = applicationId;
        return this;
    }

    /**
     * Returns applicationId.
     * <p>
     * Field description:
     * Required for application use in a send request for outbound traffic. Returned in notification events.
     *
     * @return applicationId
     */
    @JsonProperty("applicationId")
    public String getApplicationId() {
        return applicationId;
    }

    /**
     * Sets applicationId.
     * <p>
     * Field description:
     * Required for application use in a send request for outbound traffic. Returned in notification events.
     *
     * @param applicationId
     */
    @JsonProperty("applicationId")
    public void setApplicationId(String applicationId) {
        this.applicationId = applicationId;
    }

    /**
     * Sets entityId.
     * <p>
     * Field description:
     * Required for entity use in a send request for outbound traffic. Returned in notification events.
     *
     * @param entityId
     * @return This {@link EmailSendMimeRequestSchema instance}.
     */
    public EmailSendMimeRequestSchema entityId(String entityId) {
        this.entityId = entityId;
        return this;
    }

    /**
     * Returns entityId.
     * <p>
     * Field description:
     * Required for entity use in a send request for outbound traffic. Returned in notification events.
     *
     * @return entityId
     */
    @JsonProperty("entityId")
    public String getEntityId() {
        return entityId;
    }

    /**
     * Sets entityId.
     * <p>
     * Field description:
     * Required for entity use in a send request for outbound traffic. Returned in notification events.
     *
     * @param entityId
     */
    @JsonProperty("entityId")
    public void setEntityId(String entityId) {
        this.entityId = entityId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EmailSendMimeRequestSchema emailSendMimeRequestSchema = (EmailSendMimeRequestSchema) o;
        return Objects.equals(this.messageId, emailSendMimeRequestSchema.messageId)
                && Objects.equals(this.bulkId, emailSendMimeRequestSchema.bulkId)
                && Objects.equals(this.from, emailSendMimeRequestSchema.from)
                && Objects.equals(this.destinations, emailSendMimeRequestSchema.destinations)
                && Objects.equals(this.mimeMessage, emailSendMimeRequestSchema.mimeMessage)
                && Objects.equals(this.intermediateReport, emailSendMimeRequestSchema.intermediateReport)
                && Objects.equals(this.notifyUrl, emailSendMimeRequestSchema.notifyUrl)
                && Objects.equals(this.notifyContentType, emailSendMimeRequestSchema.notifyContentType)
                && Objects.equals(this.callbackData, emailSendMimeRequestSchema.callbackData)
                && Objects.equals(this.trackingUrl, emailSendMimeRequestSchema.trackingUrl)
                && Objects.equals(this.clientPriority, emailSendMimeRequestSchema.clientPriority)
                && Objects.equals(this.applicationId, emailSendMimeRequestSchema.applicationId)
                && Objects.equals(this.entityId, emailSendMimeRequestSchema.entityId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                messageId,
                bulkId,
                from,
                destinations,
                mimeMessage,
                intermediateReport,
                notifyUrl,
                notifyContentType,
                callbackData,
                trackingUrl,
                clientPriority,
                applicationId,
                entityId);
    }

    @Override
    public String toString() {
        String newLine = System.lineSeparator();
        return new StringBuilder()
                .append("class EmailSendMimeRequestSchema {")
                .append(newLine)
                .append("    messageId: ")
                .append(toIndentedString(messageId))
                .append(newLine)
                .append("    bulkId: ")
                .append(toIndentedString(bulkId))
                .append(newLine)
                .append("    from: ")
                .append(toIndentedString(from))
                .append(newLine)
                .append("    destinations: ")
                .append(toIndentedString(destinations))
                .append(newLine)
                .append("    mimeMessage: ")
                .append(toIndentedString(mimeMessage))
                .append(newLine)
                .append("    intermediateReport: ")
                .append(toIndentedString(intermediateReport))
                .append(newLine)
                .append("    notifyUrl: ")
                .append(toIndentedString(notifyUrl))
                .append(newLine)
                .append("    notifyContentType: ")
                .append(toIndentedString(notifyContentType))
                .append(newLine)
                .append("    callbackData: ")
                .append(toIndentedString(callbackData))
                .append(newLine)
                .append("    trackingUrl: ")
                .append(toIndentedString(trackingUrl))
                .append(newLine)
                .append("    clientPriority: ")
                .append(toIndentedString(clientPriority))
                .append(newLine)
                .append("    applicationId: ")
                .append(toIndentedString(applicationId))
                .append(newLine)
                .append("    entityId: ")
                .append(toIndentedString(entityId))
                .append(newLine)
                .append("}")
                .toString();
    }

    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        String lineSeparator = System.lineSeparator();
        String lineSeparatorFollowedByIndentation = lineSeparator + "    ";
        return o.toString().replace(lineSeparator, lineSeparatorFollowedByIndentation);
    }
}
