/*
 * This class is auto generated from the Infobip OpenAPI specification
 * through the OpenAPI Specification Client API libraries (Re)Generator (OSCAR),
 * powered by the OpenAPI Generator (https://openapi-generator.tech).
 *
 * Do not edit manually. To learn how to raise an issue, see the CONTRIBUTING guide
 * or contact us @ support@infobip.com.
 */

package com.infobip.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Represents MessagesApiWebhookEventPaymentResponseContent model.
 */
public class MessagesApiWebhookEventPaymentResponseContent extends MessagesApiWebhookEventContent {

    private String referenceId;

    private String paymentId;

    private String status;

    private MessagesApiWebhookEventPaymentTotal total;

    private MessagesApiWebhookEventPaymentTransaction transaction;

    private List<MessagesApiWebhookEventPaymentItem> items = null;

    /**
     * Constructs a new {@link MessagesApiWebhookEventPaymentResponseContent} instance.
     */
    public MessagesApiWebhookEventPaymentResponseContent() {
        super("PAYMENT_RESPONSE");
    }

    /**
     * Sets referenceId.
     * <p>
     * Field description:
     * (WhatsApp specific) Unique identifier generated by the payment service provider.
     *
     * @param referenceId
     * @return This {@link MessagesApiWebhookEventPaymentResponseContent instance}.
     */
    public MessagesApiWebhookEventPaymentResponseContent referenceId(String referenceId) {
        this.referenceId = referenceId;
        return this;
    }

    /**
     * Returns referenceId.
     * <p>
     * Field description:
     * (WhatsApp specific) Unique identifier generated by the payment service provider.
     *
     * @return referenceId
     */
    @JsonProperty("referenceId")
    public String getReferenceId() {
        return referenceId;
    }

    /**
     * Sets referenceId.
     * <p>
     * Field description:
     * (WhatsApp specific) Unique identifier generated by the payment service provider.
     *
     * @param referenceId
     */
    @JsonProperty("referenceId")
    public void setReferenceId(String referenceId) {
        this.referenceId = referenceId;
    }

    /**
     * Sets paymentId.
     * <p>
     * Field description:
     * (WhatsApp specific) Unique identifier of the payment.
     *
     * @param paymentId
     * @return This {@link MessagesApiWebhookEventPaymentResponseContent instance}.
     */
    public MessagesApiWebhookEventPaymentResponseContent paymentId(String paymentId) {
        this.paymentId = paymentId;
        return this;
    }

    /**
     * Returns paymentId.
     * <p>
     * Field description:
     * (WhatsApp specific) Unique identifier of the payment.
     *
     * @return paymentId
     */
    @JsonProperty("paymentId")
    public String getPaymentId() {
        return paymentId;
    }

    /**
     * Sets paymentId.
     * <p>
     * Field description:
     * (WhatsApp specific) Unique identifier of the payment.
     *
     * @param paymentId
     */
    @JsonProperty("paymentId")
    public void setPaymentId(String paymentId) {
        this.paymentId = paymentId;
    }

    /**
     * Sets status.
     * <p>
     * Field description:
     * Status of the payment.
     * <p>
     * The field is required.
     *
     * @param status
     * @return This {@link MessagesApiWebhookEventPaymentResponseContent instance}.
     */
    public MessagesApiWebhookEventPaymentResponseContent status(String status) {
        this.status = status;
        return this;
    }

    /**
     * Returns status.
     * <p>
     * Field description:
     * Status of the payment.
     * <p>
     * The field is required.
     *
     * @return status
     */
    @JsonProperty("status")
    public String getStatus() {
        return status;
    }

    /**
     * Sets status.
     * <p>
     * Field description:
     * Status of the payment.
     * <p>
     * The field is required.
     *
     * @param status
     */
    @JsonProperty("status")
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Sets total.
     * <p>
     * The field is required.
     *
     * @param total
     * @return This {@link MessagesApiWebhookEventPaymentResponseContent instance}.
     */
    public MessagesApiWebhookEventPaymentResponseContent total(MessagesApiWebhookEventPaymentTotal total) {
        this.total = total;
        return this;
    }

    /**
     * Returns total.
     * <p>
     * The field is required.
     *
     * @return total
     */
    @JsonProperty("total")
    public MessagesApiWebhookEventPaymentTotal getTotal() {
        return total;
    }

    /**
     * Sets total.
     * <p>
     * The field is required.
     *
     * @param total
     */
    @JsonProperty("total")
    public void setTotal(MessagesApiWebhookEventPaymentTotal total) {
        this.total = total;
    }

    /**
     * Sets transaction.
     *
     * @param transaction
     * @return This {@link MessagesApiWebhookEventPaymentResponseContent instance}.
     */
    public MessagesApiWebhookEventPaymentResponseContent transaction(
            MessagesApiWebhookEventPaymentTransaction transaction) {
        this.transaction = transaction;
        return this;
    }

    /**
     * Returns transaction.
     *
     * @return transaction
     */
    @JsonProperty("transaction")
    public MessagesApiWebhookEventPaymentTransaction getTransaction() {
        return transaction;
    }

    /**
     * Sets transaction.
     *
     * @param transaction
     */
    @JsonProperty("transaction")
    public void setTransaction(MessagesApiWebhookEventPaymentTransaction transaction) {
        this.transaction = transaction;
    }

    /**
     * Sets items.
     * <p>
     * Field description:
     * Items information included in the incoming message.
     *
     * @param items
     * @return This {@link MessagesApiWebhookEventPaymentResponseContent instance}.
     */
    public MessagesApiWebhookEventPaymentResponseContent items(List<MessagesApiWebhookEventPaymentItem> items) {
        this.items = items;
        return this;
    }

    /**
     * Adds and item into items.
     * <p>
     * Field description:
     * Items information included in the incoming message.
     *
     * @param itemsItem The item to be added to the list.
     * @return This {@link MessagesApiWebhookEventPaymentResponseContent instance}.
     */
    public MessagesApiWebhookEventPaymentResponseContent addItemsItem(MessagesApiWebhookEventPaymentItem itemsItem) {
        if (this.items == null) {
            this.items = new ArrayList<>();
        }
        this.items.add(itemsItem);
        return this;
    }

    /**
     * Returns items.
     * <p>
     * Field description:
     * Items information included in the incoming message.
     *
     * @return items
     */
    @JsonProperty("items")
    public List<MessagesApiWebhookEventPaymentItem> getItems() {
        return items;
    }

    /**
     * Sets items.
     * <p>
     * Field description:
     * Items information included in the incoming message.
     *
     * @param items
     */
    @JsonProperty("items")
    public void setItems(List<MessagesApiWebhookEventPaymentItem> items) {
        this.items = items;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MessagesApiWebhookEventPaymentResponseContent messagesApiWebhookEventPaymentResponseContent =
                (MessagesApiWebhookEventPaymentResponseContent) o;
        return Objects.equals(this.referenceId, messagesApiWebhookEventPaymentResponseContent.referenceId)
                && Objects.equals(this.paymentId, messagesApiWebhookEventPaymentResponseContent.paymentId)
                && Objects.equals(this.status, messagesApiWebhookEventPaymentResponseContent.status)
                && Objects.equals(this.total, messagesApiWebhookEventPaymentResponseContent.total)
                && Objects.equals(this.transaction, messagesApiWebhookEventPaymentResponseContent.transaction)
                && Objects.equals(this.items, messagesApiWebhookEventPaymentResponseContent.items)
                && super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(referenceId, paymentId, status, total, transaction, items, super.hashCode());
    }

    @Override
    public String toString() {
        String newLine = System.lineSeparator();
        return new StringBuilder()
                .append("class MessagesApiWebhookEventPaymentResponseContent {")
                .append(newLine)
                .append("    ")
                .append(toIndentedString(super.toString()))
                .append(newLine)
                .append("    referenceId: ")
                .append(toIndentedString(referenceId))
                .append(newLine)
                .append("    paymentId: ")
                .append(toIndentedString(paymentId))
                .append(newLine)
                .append("    status: ")
                .append(toIndentedString(status))
                .append(newLine)
                .append("    total: ")
                .append(toIndentedString(total))
                .append(newLine)
                .append("    transaction: ")
                .append(toIndentedString(transaction))
                .append(newLine)
                .append("    items: ")
                .append(toIndentedString(items))
                .append(newLine)
                .append("}")
                .toString();
    }

    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        String lineSeparator = System.lineSeparator();
        String lineSeparatorFollowedByIndentation = lineSeparator + "    ";
        return o.toString().replace(lineSeparator, lineSeparatorFollowedByIndentation);
    }
}
