/*
 * This class is auto generated from the Infobip OpenAPI specification
 * through the OpenAPI Specification Client API libraries (Re)Generator (OSCAR),
 * powered by the OpenAPI Generator (https://openapi-generator.tech).
 *
 * Do not edit manually. To learn how to raise an issue, see the CONTRIBUTING guide
 * or contact us @ support@infobip.com.
 */

package com.infobip.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * [The status](https://www.infobip.com/docs/essentials/api-essentials/response-status-and-error-codes) of RCS capability check request for the specified phone number.
 */
public enum RcsStatusReason {
    PENDING_TIME_VIOLATION("PENDING_TIME_VIOLATION"),
    DELIVERED_TO_OPERATOR("DELIVERED_TO_OPERATOR"),
    PENDING_WAITING_DELIVERY("PENDING_WAITING_DELIVERY"),
    UNDELIVERABLE_REJECTED_OPERATOR("UNDELIVERABLE_REJECTED_OPERATOR"),
    DELIVERED_TO_HANDSET("DELIVERED_TO_HANDSET"),
    REJECTED_NETWORK("REJECTED_NETWORK"),
    PENDING_ENROUTE("PENDING_ENROUTE"),
    REJECTED_PREFIX_MISSING("REJECTED_PREFIX_MISSING"),
    UNDELIVERABLE_NOT_DELIVERED("UNDELIVERABLE_NOT_DELIVERED"),
    REJECTED_DND("REJECTED_DND"),
    REJECTED_SOURCE("REJECTED_SOURCE"),
    REJECTED_NOT_ENOUGH_CREDITS("REJECTED_NOT_ENOUGH_CREDITS"),
    REJECTED_SENDER("REJECTED_SENDER"),
    REJECTED_DESTINATION("REJECTED_DESTINATION"),
    EXPIRED_EXPIRED("EXPIRED_EXPIRED"),
    REJECTED_NOT_REACHABLE("REJECTED_NOT_REACHABLE"),
    REJECTED_PREPAID_PACKAGE_EXPIRED("REJECTED_PREPAID_PACKAGE_EXPIRED"),
    REJECTED_DESTINATION_NOT_REGISTERED("REJECTED_DESTINATION_NOT_REGISTERED"),
    REJECTED_ROUTE_NOT_AVAILABLE("REJECTED_ROUTE_NOT_AVAILABLE"),
    REJECTED_FLOODING_FILTER("REJECTED_FLOODING_FILTER"),
    REJECTED_SYSTEM_ERROR("REJECTED_SYSTEM_ERROR"),
    EXPIRED_UNKNOWN("EXPIRED_UNKNOWN"),
    REJECTED_DUPLICATE_MESSAGE_ID("REJECTED_DUPLICATE_MESSAGE_ID"),
    REJECTED_INVALID_UDH("REJECTED_INVALID_UDH"),
    REJECTED_MESSAGE_TOO_LONG("REJECTED_MESSAGE_TOO_LONG"),
    REJECTED_NOT_SENT("REJECTED_NOT_SENT"),
    EXPIRED_DLR_UNKNOWN("EXPIRED_DLR_UNKNOWN"),
    MO_DELIVERED("MO_DELIVERED"),
    UNDELIVERABLE_NOT_SENT("UNDELIVERABLE_NOT_SENT"),
    MISSING_TO("MISSING_TO"),
    INVALID_DESTINATION_ADDRESS("INVALID_DESTINATION_ADDRESS"),
    CONCATENATED_MESSAGE_TOO_LONG("CONCATENATED_MESSAGE_TOO_LONG"),
    REJECTED_MONTHLY_LIMIT_REACHED("REJECTED_MONTHLY_LIMIT_REACHED"),
    REJECTED_SMPP_SESSION_CLOSED("REJECTED_SMPP_SESSION_CLOSED"),
    INVALID_SUBACCOUNT_NAME("INVALID_SUBACCOUNT_NAME"),
    REJECTED_GATEWAY_DATA_TOO_LONG("REJECTED_GATEWAY_DATA_TOO_LONG"),
    INVALID_COMPANY_ID("INVALID_COMPANY_ID"),
    REJECTED_INVALID_TRACKING_DATA("REJECTED_INVALID_TRACKING_DATA"),
    REJECTED_INVALID_COUNT("REJECTED_INVALID_COUNT"),
    REJECTED_FREE_TRIAL_EXCEEDED("REJECTED_FREE_TRIAL_EXCEEDED"),
    REJECTED_SUBSCRIPTION_PLAN_NOT_ACTIVE("REJECTED_SUBSCRIPTION_PLAN_NOT_ACTIVE"),
    SIM_SWAP_DETECTED("SIM_SWAP_DETECTED"),
    DEACTIVATED_LIST("DEACTIVATED_LIST"),
    INVALID_CLIENT_NETWORK("INVALID_CLIENT_NETWORK"),
    CURRENCY_CHANGE_IN_PROGRESS("CURRENCY_CHANGE_IN_PROGRESS"),
    REJECTED_UNREACHABLE_DESTINATION("REJECTED_UNREACHABLE_DESTINATION"),
    SIGNALS_BLOCKED("SIGNALS_BLOCKED"),
    VOLUMETRIC_BLOCKED("VOLUMETRIC_BLOCKED"),
    REJECTED_BLOCKED_TEMPLATE("REJECTED_BLOCKED_TEMPLATE"),
    REJECTED_INVALID_PLATFORM_PARAMETERS("REJECTED_INVALID_PLATFORM_PARAMETERS"),
    REJECTED_SHORT_DOMAIN_NOT_VERIFIED("REJECTED_SHORT_DOMAIN_NOT_VERIFIED"),
    REJECTED_10DLC_LIMIT_REACHED("REJECTED_10DLC_LIMIT_REACHED"),
    REJECTED_INVALID_BYO_EXTERNAL_ID("REJECTED_INVALID_BYO_EXTERNAL_ID");

    private final String value;

    RcsStatusReason(String value) {
        this.value = value;
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
    public static RcsStatusReason fromValue(String value) {
        for (RcsStatusReason enumElement : RcsStatusReason.values()) {
            if (enumElement.value.equals(value)) {
                return enumElement;
            }
        }
        throw new IllegalArgumentException("Unexpected enum value '" + value + "'.");
    }
}
