/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.infobip.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/** Gets or Sets SmsBulkStatus */
@JsonAdapter(SmsBulkStatus.Adapter.class)
public enum SmsBulkStatus {
  PENDING("PENDING"),

  PAUSED("PAUSED"),

  PROCESSING("PROCESSING"),

  CANCELED("CANCELED"),

  FINISHED("FINISHED"),

  FAILED("FAILED");

  private String value;

  SmsBulkStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static SmsBulkStatus fromValue(String value) {
    for (SmsBulkStatus b : SmsBulkStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<SmsBulkStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final SmsBulkStatus enumeration)
        throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public SmsBulkStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return SmsBulkStatus.fromValue(value);
    }
  }
}
