/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.infobip.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/** Gets or Sets SmsDeliveryDay */
@JsonAdapter(SmsDeliveryDay.Adapter.class)
public enum SmsDeliveryDay {
  MONDAY("MONDAY"),

  TUESDAY("TUESDAY"),

  WEDNESDAY("WEDNESDAY"),

  THURSDAY("THURSDAY"),

  FRIDAY("FRIDAY"),

  SATURDAY("SATURDAY"),

  SUNDAY("SUNDAY");

  private String value;

  SmsDeliveryDay(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static SmsDeliveryDay fromValue(String value) {
    for (SmsDeliveryDay b : SmsDeliveryDay.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<SmsDeliveryDay> {
    @Override
    public void write(final JsonWriter jsonWriter, final SmsDeliveryDay enumeration)
        throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public SmsDeliveryDay read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return SmsDeliveryDay.fromValue(value);
    }
  }
}
