/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.infobip.model;

import com.google.gson.annotations.SerializedName;
import java.util.Objects;

/** SmsDeliveryTime */
public class SmsDeliveryTime {
  public static final String SERIALIZED_NAME_HOUR = "hour";

  @SerializedName(SERIALIZED_NAME_HOUR)
  private Integer hour;

  public static final String SERIALIZED_NAME_MINUTE = "minute";

  @SerializedName(SERIALIZED_NAME_MINUTE)
  private Integer minute;

  public SmsDeliveryTime hour(Integer hour) {

    this.hour = hour;
    return this;
  }

  /**
   * Hour when the time window opens when used in from property or closes when used into the
   * property.
   *
   * @return hour
   */
  public Integer getHour() {
    return hour;
  }

  public void setHour(Integer hour) {
    this.hour = hour;
  }

  public SmsDeliveryTime minute(Integer minute) {

    this.minute = minute;
    return this;
  }

  /**
   * Minute when the time window opens when used in from property or closes when used into the
   * property.
   *
   * @return minute
   */
  public Integer getMinute() {
    return minute;
  }

  public void setMinute(Integer minute) {
    this.minute = minute;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SmsDeliveryTime smsDeliveryTime = (SmsDeliveryTime) o;
    return Objects.equals(this.hour, smsDeliveryTime.hour)
        && Objects.equals(this.minute, smsDeliveryTime.minute);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hour, minute);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SmsDeliveryTime {\n");
    sb.append("    hour: ").append(toIndentedString(hour)).append("\n");
    sb.append("    minute: ").append(toIndentedString(minute)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
