/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.infobip.model;

import com.google.gson.annotations.SerializedName;
import java.util.Objects;

/** SmsError */
public class SmsError {
  public static final String SERIALIZED_NAME_DESCRIPTION = "description";

  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_PERMANENT = "permanent";

  @SerializedName(SERIALIZED_NAME_PERMANENT)
  private Boolean permanent;

  public static final String SERIALIZED_NAME_ID = "id";

  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_GROUP_ID = "groupId";

  @SerializedName(SERIALIZED_NAME_GROUP_ID)
  private Integer groupId;

  public static final String SERIALIZED_NAME_GROUP_NAME = "groupName";

  @SerializedName(SERIALIZED_NAME_GROUP_NAME)
  private String groupName;

  public static final String SERIALIZED_NAME_NAME = "name";

  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  /**
   * Human-readable description of the error..
   *
   * @return description
   */
  public String getDescription() {
    return description;
  }

  /**
   * Tells if the error is permanent.
   *
   * @return permanent
   */
  public Boolean getPermanent() {
    return permanent;
  }

  /**
   * Error ID.
   *
   * @return id
   */
  public Integer getId() {
    return id;
  }

  /**
   * Error group ID.
   *
   * @return groupId
   */
  public Integer getGroupId() {
    return groupId;
  }

  /**
   * Error group name.
   *
   * @return groupName
   */
  public String getGroupName() {
    return groupName;
  }

  /**
   * Error name.
   *
   * @return name
   */
  public String getName() {
    return name;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SmsError smsError = (SmsError) o;
    return Objects.equals(this.description, smsError.description)
        && Objects.equals(this.permanent, smsError.permanent)
        && Objects.equals(this.id, smsError.id)
        && Objects.equals(this.groupId, smsError.groupId)
        && Objects.equals(this.groupName, smsError.groupName)
        && Objects.equals(this.name, smsError.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, permanent, id, groupId, groupName, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SmsError {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    permanent: ").append(toIndentedString(permanent)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    groupName: ").append(toIndentedString(groupName)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
