/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.infobip.model;

import com.google.gson.annotations.SerializedName;
import java.util.Objects;

/** SmsResponseDetails */
public class SmsResponseDetails {
  public static final String SERIALIZED_NAME_MESSAGE_ID = "messageId";

  @SerializedName(SERIALIZED_NAME_MESSAGE_ID)
  private String messageId;

  public static final String SERIALIZED_NAME_STATUS = "status";

  @SerializedName(SERIALIZED_NAME_STATUS)
  private SmsStatus status = null;

  public static final String SERIALIZED_NAME_TO = "to";

  @SerializedName(SERIALIZED_NAME_TO)
  private String to;

  /**
   * Unique message ID. If not passed, it will be automatically generated and returned in a
   * response.
   *
   * @return messageId
   */
  public String getMessageId() {
    return messageId;
  }

  /**
   * Indicates the
   * [status](https://www.infobip.com/docs/essentials/response-status-and-error-codes#api-status-codes)
   * of the message and how to recover from an error should there be any.
   *
   * @return status
   */
  public SmsStatus getStatus() {
    return status;
  }

  /**
   * The destination address of the message.
   *
   * @return to
   */
  public String getTo() {
    return to;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SmsResponseDetails smsResponseDetails = (SmsResponseDetails) o;
    return Objects.equals(this.messageId, smsResponseDetails.messageId)
        && Objects.equals(this.status, smsResponseDetails.status)
        && Objects.equals(this.to, smsResponseDetails.to);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messageId, status, to);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SmsResponseDetails {\n");
    sb.append("    messageId: ").append(toIndentedString(messageId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
