/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.infobip.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/** Gets or Sets SmsSpeedLimitTimeUnit */
@JsonAdapter(SmsSpeedLimitTimeUnit.Adapter.class)
public enum SmsSpeedLimitTimeUnit {
  MINUTE("MINUTE"),

  HOUR("HOUR"),

  DAY("DAY");

  private String value;

  SmsSpeedLimitTimeUnit(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static SmsSpeedLimitTimeUnit fromValue(String value) {
    for (SmsSpeedLimitTimeUnit b : SmsSpeedLimitTimeUnit.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<SmsSpeedLimitTimeUnit> {
    @Override
    public void write(final JsonWriter jsonWriter, final SmsSpeedLimitTimeUnit enumeration)
        throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public SmsSpeedLimitTimeUnit read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return SmsSpeedLimitTimeUnit.fromValue(value);
    }
  }
}
