/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.infobip.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/** Gets or Sets TfaLanguage */
@JsonAdapter(TfaLanguage.Adapter.class)
public enum TfaLanguage {
  EN("en"),

  ES("es"),

  CA("ca"),

  DA("da"),

  NL("nl"),

  FR("fr"),

  DE("de"),

  IT("it"),

  JA("ja"),

  KO("ko"),

  NO("no"),

  PL("pl"),

  RU("ru"),

  SV("sv"),

  FI("fi"),

  PT_PT("pt-pt"),

  PT_BR("pt-br"),

  ZH_CN("zh-cn"),

  ZH_TW("zh-tw");

  private String value;

  TfaLanguage(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static TfaLanguage fromValue(String value) {
    for (TfaLanguage b : TfaLanguage.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<TfaLanguage> {
    @Override
    public void write(final JsonWriter jsonWriter, final TfaLanguage enumeration)
        throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public TfaLanguage read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return TfaLanguage.fromValue(value);
    }
  }
}
