/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.infobip.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/** Gets or Sets TfaPinType */
@JsonAdapter(TfaPinType.Adapter.class)
public enum TfaPinType {
  NUMERIC("NUMERIC"),

  ALPHA("ALPHA"),

  HEX("HEX"),

  ALPHANUMERIC("ALPHANUMERIC");

  private String value;

  TfaPinType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static TfaPinType fromValue(String value) {
    for (TfaPinType b : TfaPinType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<TfaPinType> {
    @Override
    public void write(final JsonWriter jsonWriter, final TfaPinType enumeration)
        throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public TfaPinType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return TfaPinType.fromValue(value);
    }
  }
}
