/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.infobip.model;

import com.google.gson.annotations.SerializedName;
import java.util.Objects;

/** Contains information about contact&#39;s company. */
public class WhatsAppOrganizationContent {
  public static final String SERIALIZED_NAME_COMPANY = "company";

  @SerializedName(SERIALIZED_NAME_COMPANY)
  private String company;

  public static final String SERIALIZED_NAME_DEPARTMENT = "department";

  @SerializedName(SERIALIZED_NAME_DEPARTMENT)
  private String department;

  public static final String SERIALIZED_NAME_TITLE = "title";

  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public WhatsAppOrganizationContent company(String company) {

    this.company = company;
    return this;
  }

  /**
   * Company name.
   *
   * @return company
   */
  public String getCompany() {
    return company;
  }

  public void setCompany(String company) {
    this.company = company;
  }

  public WhatsAppOrganizationContent department(String department) {

    this.department = department;
    return this;
  }

  /**
   * Department name.
   *
   * @return department
   */
  public String getDepartment() {
    return department;
  }

  public void setDepartment(String department) {
    this.department = department;
  }

  public WhatsAppOrganizationContent title(String title) {

    this.title = title;
    return this;
  }

  /**
   * Title value.
   *
   * @return title
   */
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WhatsAppOrganizationContent whatsAppOrganizationContent = (WhatsAppOrganizationContent) o;
    return Objects.equals(this.company, whatsAppOrganizationContent.company)
        && Objects.equals(this.department, whatsAppOrganizationContent.department)
        && Objects.equals(this.title, whatsAppOrganizationContent.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(company, department, title);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WhatsAppOrganizationContent {\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    department: ").append(toIndentedString(department)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
