/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.infobip.model;

import com.google.gson.annotations.SerializedName;
import java.util.Objects;

/** WhatsAppInteractiveReplyButtonContent */
public class WhatsAppInteractiveReplyButtonContent extends WhatsAppInteractiveButtonContent {
  public static final String SERIALIZED_NAME_ID = "id";

  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_TITLE = "title";

  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public WhatsAppInteractiveReplyButtonContent id(String id) {

    this.id = id;
    return this;
  }

  /**
   * Unique identifier of the button.
   *
   * @return id
   */
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public WhatsAppInteractiveReplyButtonContent title(String title) {

    this.title = title;
    return this;
  }

  /**
   * Unique title of the button. Doesn&#39;t allow emojis or markdown.
   *
   * @return title
   */
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WhatsAppInteractiveReplyButtonContent whatsAppInteractiveReplyButtonContent =
        (WhatsAppInteractiveReplyButtonContent) o;
    return Objects.equals(this.id, whatsAppInteractiveReplyButtonContent.id)
        && Objects.equals(this.title, whatsAppInteractiveReplyButtonContent.title)
        && super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, title, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WhatsAppInteractiveReplyButtonContent {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
