/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.infobip.model;

import com.google.gson.annotations.SerializedName;
import java.util.Objects;

/** WhatsAppPhoneNumberButtonApiData */
public class WhatsAppPhoneNumberButtonApiData extends WhatsAppButtonApiData {
  public static final String SERIALIZED_NAME_PHONE_NUMBER = "phoneNumber";

  @SerializedName(SERIALIZED_NAME_PHONE_NUMBER)
  private String phoneNumber;

  public WhatsAppPhoneNumberButtonApiData phoneNumber(String phoneNumber) {

    this.phoneNumber = phoneNumber;
    return this;
  }

  /**
   * Phone number to which a phone call would be placed by end-user when hitting the button.
   *
   * @return phoneNumber
   */
  public String getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WhatsAppPhoneNumberButtonApiData whatsAppPhoneNumberButtonApiData =
        (WhatsAppPhoneNumberButtonApiData) o;
    return Objects.equals(this.phoneNumber, whatsAppPhoneNumberButtonApiData.phoneNumber)
        && super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(phoneNumber, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WhatsAppPhoneNumberButtonApiData {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
