/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.infobip.model;

import com.google.gson.annotations.SerializedName;
import java.util.Objects;

/** Information about the message to which the end user responded. */
public class WhatsAppContext {
  public static final String SERIALIZED_NAME_ID = "id";

  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_FROM = "from";

  @SerializedName(SERIALIZED_NAME_FROM)
  private String from;

  public static final String SERIALIZED_NAME_REFERRED_PRODUCT = "referredProduct";

  @SerializedName(SERIALIZED_NAME_REFERRED_PRODUCT)
  private WhatsAppReferredProduct referredProduct;

  public WhatsAppContext id(String id) {

    this.id = id;
    return this;
  }

  /**
   * MessageId of the message to which the end user responded.
   *
   * @return id
   */
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public WhatsAppContext from(String from) {

    this.from = from;
    return this;
  }

  /**
   * End user&#39;s phone number.
   *
   * @return from
   */
  public String getFrom() {
    return from;
  }

  public void setFrom(String from) {
    this.from = from;
  }

  public WhatsAppContext referredProduct(WhatsAppReferredProduct referredProduct) {

    this.referredProduct = referredProduct;
    return this;
  }

  /**
   * Get referredProduct
   *
   * @return referredProduct
   */
  public WhatsAppReferredProduct getReferredProduct() {
    return referredProduct;
  }

  public void setReferredProduct(WhatsAppReferredProduct referredProduct) {
    this.referredProduct = referredProduct;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WhatsAppContext whatsAppContext = (WhatsAppContext) o;
    return Objects.equals(this.id, whatsAppContext.id)
        && Objects.equals(this.from, whatsAppContext.from)
        && Objects.equals(this.referredProduct, whatsAppContext.referredProduct);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, from, referredProduct);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WhatsAppContext {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    referredProduct: ").append(toIndentedString(referredProduct)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
