/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.infobip.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/** Type of the message content. Select the type from the dropbox to view their parameters. */
@JsonAdapter(WhatsAppType.Adapter.class)
public enum WhatsAppType {
  TEXT("TEXT"),

  IMAGE("IMAGE"),

  DOCUMENT("DOCUMENT"),

  STICKER("STICKER"),

  LOCATION("LOCATION"),

  CONTACT("CONTACT"),

  VIDEO("VIDEO"),

  VOICE("VOICE"),

  AUDIO("AUDIO"),

  BUTTON("BUTTON"),

  INTERACTIVE_BUTTON_REPLY("INTERACTIVE_BUTTON_REPLY"),

  INTERACTIVE_LIST_REPLY("INTERACTIVE_LIST_REPLY"),

  ORDER("ORDER"),

  UNSUPPORTED("UNSUPPORTED");

  private String value;

  WhatsAppType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static WhatsAppType fromValue(String value) {
    for (WhatsAppType b : WhatsAppType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<WhatsAppType> {
    @Override
    public void write(final JsonWriter jsonWriter, final WhatsAppType enumeration)
        throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public WhatsAppType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return WhatsAppType.fromValue(value);
    }
  }
}
