/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.infobip.model;

import com.google.gson.annotations.SerializedName;
import java.util.Objects;

/** Array of addresses information. */
public class WhatsAppAddressContent {
  public static final String SERIALIZED_NAME_STREET = "street";

  @SerializedName(SERIALIZED_NAME_STREET)
  private String street;

  public static final String SERIALIZED_NAME_CITY = "city";

  @SerializedName(SERIALIZED_NAME_CITY)
  private String city;

  public static final String SERIALIZED_NAME_STATE = "state";

  @SerializedName(SERIALIZED_NAME_STATE)
  private String state;

  public static final String SERIALIZED_NAME_ZIP = "zip";

  @SerializedName(SERIALIZED_NAME_ZIP)
  private String zip;

  public static final String SERIALIZED_NAME_COUNTRY = "country";

  @SerializedName(SERIALIZED_NAME_COUNTRY)
  private String country;

  public static final String SERIALIZED_NAME_COUNTRY_CODE = "countryCode";

  @SerializedName(SERIALIZED_NAME_COUNTRY_CODE)
  private String countryCode;

  public static final String SERIALIZED_NAME_TYPE = "type";

  @SerializedName(SERIALIZED_NAME_TYPE)
  private WhatsAppAddressType type;

  public WhatsAppAddressContent street(String street) {

    this.street = street;
    return this;
  }

  /**
   * Street name.
   *
   * @return street
   */
  public String getStreet() {
    return street;
  }

  public void setStreet(String street) {
    this.street = street;
  }

  public WhatsAppAddressContent city(String city) {

    this.city = city;
    return this;
  }

  /**
   * City name.
   *
   * @return city
   */
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public WhatsAppAddressContent state(String state) {

    this.state = state;
    return this;
  }

  /**
   * State name.
   *
   * @return state
   */
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public WhatsAppAddressContent zip(String zip) {

    this.zip = zip;
    return this;
  }

  /**
   * Zip code value.
   *
   * @return zip
   */
  public String getZip() {
    return zip;
  }

  public void setZip(String zip) {
    this.zip = zip;
  }

  public WhatsAppAddressContent country(String country) {

    this.country = country;
    return this;
  }

  /**
   * Country name.
   *
   * @return country
   */
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public WhatsAppAddressContent countryCode(String countryCode) {

    this.countryCode = countryCode;
    return this;
  }

  /**
   * Country code value.
   *
   * @return countryCode
   */
  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }

  public WhatsAppAddressContent type(WhatsAppAddressType type) {

    this.type = type;
    return this;
  }

  /**
   * Get type
   *
   * @return type
   */
  public WhatsAppAddressType getType() {
    return type;
  }

  public void setType(WhatsAppAddressType type) {
    this.type = type;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WhatsAppAddressContent whatsAppAddressContent = (WhatsAppAddressContent) o;
    return Objects.equals(this.street, whatsAppAddressContent.street)
        && Objects.equals(this.city, whatsAppAddressContent.city)
        && Objects.equals(this.state, whatsAppAddressContent.state)
        && Objects.equals(this.zip, whatsAppAddressContent.zip)
        && Objects.equals(this.country, whatsAppAddressContent.country)
        && Objects.equals(this.countryCode, whatsAppAddressContent.countryCode)
        && Objects.equals(this.type, whatsAppAddressContent.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(street, city, state, zip, country, countryCode, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WhatsAppAddressContent {\n");
    sb.append("    street: ").append(toIndentedString(street)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    zip: ").append(toIndentedString(zip)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
