name: SonarCloud analysis

on: [push]

jobs:
  sonarcloud:
    name: SonarCloud analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven
      - name: Sonarcloud code analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -B verify sonar:sonar \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=infobip \
          -Dsonar.projectKey=infobip_infobip-api-java-client \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
